#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\Tools\Resources\build.ps1
  

# Install
install:
#  - git submodule update --init --recursive+ 
  - git submodule init
  - git submodule sync
  - dir /s

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Tools -> build.ps1