#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\Tools\Resources\build.ps1
  

# Install
install:
#  - git submodule update --init --recursive+ 
#  - git submodule sync
#  - git submodule update --init --recursive
  - dir /s

clone_script:
- cmd: git clone -q https://github.com/$env:appveyor_repo_name.git $env:appveyor_build_folder
- cmd: git fetch -q origin +refs/pull/$env:appveyor_pull_request_number/merge:
- cmd: git checkout -qf FETCH_HEAD
- cmd: dir /s
# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Tools -> build.ps1